# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  option: value
# output configuration options
output:
  # See the dedicated "output" documentation section.
  option: value
# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.
  option: value
linters:
  # See the dedicated "linters" documentation section.
  option: value
issues:
  exclude-rules:
    - path: tls.go
      linters:
        - staticcheck
      text: SA1019
severity:
  # See the dedicated "severity" documentation section.
  option: value